opentelemetry-collector:
  extraContainers:
    - name: tails
      image: ghcr.io/jaronoff97/tails:v0.0.8
      env:
        - name: SECRET_KEY_BASE
          value: ycLPy0iMVR1IYyttJX0CytDkyFWejKLzNBEvvd35UYwlc5CYZkDbs/FRU07xLbVeVtteVk/zDH0HGxc1Gz/saA==
      ports:
        - containerPort: 4000
  config:
    extensions:
      opamp:
        server:
          ws:
            endpoint: ws://127.0.0.1:4000/v1/opamp
            tls:
              insecure: true
    processors:
      remotetap:
        endpoint: localhost:12001
        limit: 5
    service:
      extensions:
        - health_check
        - opamp
      pipelines:
        logs:
          exporters:
            - opensearch
            - debug
          processors:
            - k8sattributes
            - memory_limiter
            - resource
            - remotetap
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - otlphttp/prometheus
            - debug
          processors:
            - k8sattributes
            - memory_limiter
            - resource
            - remotetap
            - batch
          receivers:
            - httpcheck/frontendproxy
            - redis
            - otlp
            - spanmetrics
        traces:
          exporters:
            - otlp
            - debug
            - spanmetrics
          processors:
            - k8sattributes
            - memory_limiter
            - resource
            - remotetap
            - batch
          receivers:
            - otlp
            - jaeger
            - zipkin
