opentelemetry-collector:
  config:
    processors:
      remotetap:
        endpoint: localhost:12001
        limit: 5
    service:
      extensions:
        - health_check
      pipelines:
        logs:
          exporters:
            - debug
          processors:
            - k8sattributes
            - memory_limiter
            - resource
            - remotetap
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - debug
          processors:
            - k8sattributes
            - memory_limiter
            - resource
            - remotetap
            - batch
          receivers:
            - httpcheck/frontendproxy
            - redis
            - otlp
            - spanmetrics
        traces:
          exporters:
            - debug
            - spanmetrics
          processors:
            - k8sattributes
            - memory_limiter
            - resource
            - remotetap
            - batch
          receivers:
            - otlp
            - jaeger
            - zipkin
